<?php
/*
Plugin Name: MSN Space Sync
Plugin URI: http://priv.tw/blog/
Description: A MSN rpc plug-in
Author: William, priv
Version: 1.0p
Author URI: http://moonblue.homeip.net
*/
?>
<?php	

//before the world starts, check functions
$extension_array=get_loaded_extensions();
if(($array_key=array_search('xmlrpc',$extension_array))!=NULL){
	$RPC_VERSION=1;
}else{
	$RPC_VERSION=-1;
}
$WP_MSNSYNC_PASSWORD;
$WP_MSNSYNC_URL;
$WP_MSNSYNC_ENABLE;
$WP_MSNSYNC_MSG;
$WP_MSNSYNC_TITLE;
$WP_MSNSYNC_COOK;
$WP_MSNSYNC_PUBLISH;

//initialize the options
if (!(get_option('wp_msnsync_enable'))) {
	add_option("wp_msnsync_url", 'fill-in-you-space-name');
	add_option("wp_msnsync_password", 'fill-in-your-password');
	add_option("wp_msnsync_enable", '1');
	add_option("wp_msnsync_cook", '1');
	add_option("wp_msnsync_publish", '1');
	add_option("wp_msnsync_msg",  '[POST]');
	add_option("wp_msnsync_title",  '[TITLE]');
}

/*Publishing hook*/
function wp_msnsync_post($input){
	//$input is the post id
	$data=get_post($input);
	//those two are some aviable data sets
	//$data->post_content;
	//$data->post_title;

	//
	$WP_MSNSYNC_ENABLE=get_option("wp_msnsync_enable");
	if($WP_MSNSYNC_ENABLE=="1"){//enable
	$request=wp_msnsync_genpost($data);
	$result=wp_msnsync_docall($request);

	}else{
	//do nothing
	}
	return $input;
}

function wp_msnsync_genpost($user_data){
	$WP_MSNSYNC_PASSWORD=get_option("wp_msnsync_password");
	$WP_MSNSYNC_URL=get_option("wp_msnsync_url");
	$WP_MSNSYNC_ENABLE=get_option("wp_msnsync_enable");
	$WP_MSNSYNC_MSG=get_option("wp_msnsync_msg");
	$WP_MSNSYNC_TITLE=get_option("wp_msnsync_title");
	$WP_MSNSYNC_COOK=get_option("wp_msnsync_cook");
	$WP_MSNSYNC_PUBLISH=get_option("wp_msnsync_publish");

//priv, do filter or the article may be unformatted
$post=apply_filters('the_content', $user_data->post_content);

//added in version 1.0
//digest of post support
$r1=array("[TITLE]","[POST]","[PERMALINK]");
$r2=array($user_data->post_title,$post, get_permalink($user_data->ID));
$WP_MSNSYNC_MSG=str_replace($r1,$r2,$WP_MSNSYNC_MSG);
//priv, add back the title digest support, don't know why orignal author don't want to do this
$WP_MSNSYNC_TITLE=str_replace($r1, $r2, $WP_MSNSYNC_TITLE);

//In MSN Spaces, <p> doesn't work quite like wordpress, hack it.
if($WP_MSNSYNC_COOK=="1")
{
	$r1=array("<p>", "</p>");
	$r2=array("<div>", "</div><br/>");
	$WP_MSNSYNC_MSG=str_replace($r1,$r2,$WP_MSNSYNC_MSG);
}
//
//fix the HTML output problem generated by MSN API
//added in version 1.0
$r1=array("&","<",">");
$r2=array("&amp;","&lt;","&gt;");
$WP_MSNSYNC_MSG=str_replace($r1,$r2,$WP_MSNSYNC_MSG);

//get categories, MSN Spaces only take first category though
$categories = get_the_category($user_data->ID);
$the_list = '';
foreach ($categories as $category) {
	$category->cat_name = convert_chars($category->cat_name);
	$the_list .="<data><value><string>$category->cat_name</string></value></data>\n";
}

$output="<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<methodCall>
<methodName>metaWeblog.newPost</methodName>
<params>
 <param>
  <value>
   <string>MyBlog</string>
  </value>
 </param>
 <param>
  <value>
   <string>".$WP_MSNSYNC_URL."</string>
  </value>
 </param>
 <param>
  <value>
   <string>".$WP_MSNSYNC_PASSWORD."</string>
  </value>
 </param>
 <param>
  <value>
   <struct>
    <member>
     <name>title</name>
     <value>
      <string>".$WP_MSNSYNC_TITLE."</string>
     </value>
    </member>
    <member>
     <name>description</name>
     <value>
      <string>".($WP_MSNSYNC_MSG)."</string>
     </value>
    </member>
    <member>
     <name>dateTime.iso8601</name>
     <value>
      <string>".ig_iso8601_time()."</string>
     </value>
    </member>
    <member>
     <name>categories</name>
     <value>
      <array>
      ".$the_list."
      </array>
     </value>
    </member>
   </struct>
  </value>
 </param>
 <param>
  <value>
   <boolean>$WP_MSNSYNC_PUBLISH</boolean>
  </value>
 </param>
</params>
</methodCall>
";

	//var_dump($result);
	
	return $output;
}
//wp_msnsync_genpost();
/*time generating function*/
function ig_iso8601_time($utc=true){
        $datestr = date('Y-m-d\TH:i:sO');
        if($utc){
                $eregStr =
                '([0-9]{4})-'.        // centuries & years CCYY-
                '([0-9]{2})-'.        // months MM-
                '([0-9]{2})'.        // days DD
                'T'.                        // separator T
                '([0-9]{2}):'.        // hours hh:
                '([0-9]{2}):'.        // minutes mm:
                '([0-9]{2})(\.[0-9]*)?'. // seconds ss.ss...
                '(Z|[+\-][0-9]{2}:?[0-9]{2})?'; // Z to indicate UTC, -/+HH:MM:SS.SS... for local tz's

                if(ereg($eregStr,$datestr,$regs)){
                        return sprintf('%04d-%02d-%02dT%02d:%02d:%02dZ',$regs[1],$regs[2],$regs[3],$regs[4],$regs[5],$regs[6]);
                }
                return false;
        } else {
                return $datestr;
        }
}

/*main action function*/
function wp_msnsync_display(){
/*First, check action*/
if($_POST['action']=="options"){
//this means there are new options, save into database
	wp_msnsync_save();
}

global $WP_MSNSYNC_PASSWORD;
global $WP_MSNSYNC_URL;
global $WP_MSNSYNC_ENABLE;
global $WP_MSNSYNC_MSG;
global $WP_MSNSYNC_TITLE;
global $WP_MSNSYNC_COOK;
global $WP_MSNSYNC_PUBLISH;

$WP_MSNSYNC_PASSWORD=get_option("wp_msnsync_password");
$WP_MSNSYNC_URL=get_option("wp_msnsync_url");
$WP_MSNSYNC_ENABLE=get_option("wp_msnsync_enable");
$WP_MSNSYNC_MSG=get_option("wp_msnsync_msg");
$WP_MSNSYNC_TITLE=get_option("wp_msnsync_title");
$WP_MSNSYNC_COOK=get_option("wp_msnsync_cook");
$WP_MSNSYNC_PUBLISH=get_option("wp_msnsync_publish");

//
//wp_msnsync_genpost();

//get info
global $RPC_VERSION;
if($RPC_VERSION==1){
	$response=wp_msnsync_getinfo();
}

?>
<div class="wrap">
	<h2>MSN Sync</h2>
	<?php
	if(isset($response['faultCode'])){
	//this means there is an error
	?>
	<div class="wrap">
	Error: <?php echo $response['faultCode']."|".$response['faultString']?>;
	</div>
	<?php
	}else{
	/*if there is no error in response, continue parsing*/
	?>
	<div class="wrap">
	<?php if($RPC_VERSION==1){?>
	Your Space: <a href="<?php echo $response[0]['url'];?>"><?php echo $response[0]['blogName']." ( ".$response[0]['blogid']." )";?></a>
	</div>
	<?php }else{?>
	<div>
	<font color="red">Your PHP build does not support built-in XML-RPC. Fucntion will be limited</font>
	<br>
	You will be able to synchronize (send message to) your msn space, but can not receive response regarding error or other infomation from it.<br>
	To enable native XMLRPC, please see further the references <a href="http://ca.php.net/manual/en/ref.xmlrpc.php">here</a>
	</div>
	<?php
	}//endif $RPC_VERSION
	}//if there is no error?>
	<br>
	<form name="msnoptions" method="post">
	<TABLE class=optiontable>
	<TBODY>
	<TR vAlign=top>
	<TH scope=row>Space Name:</TH><td><input name="URL" type="text" size="60" value="<?php echo  $WP_MSNSYNC_URL;?>" /><br />Make sure you enter the space name, not the URL.<br />e.g. "http://spaces.msn.com/abcd" should enter "abcd"</td>
	</TR>
	<tr valign="top">
	<th scope="row">Password:</th><td> <input name="PASS" type="text" size="60" value="<?php echo  $WP_MSNSYNC_PASSWORD;?>"/><br />This is the secret word you choosed in your MSN space</td></tr>
	<tr valign="top">
	<th scope="row">Enable Sync: </th><td>
	<?php if($WP_MSNSYNC_ENABLE=="1"){?>
	  <label><input type="radio" name="ENABLE" value="1" checked/>Yes</label>
	  <label><input type="radio" name="ENABLE" value="0" />No</label>
	  <?php }else{ ?>
  	  <label><input type="radio" name="ENABLE" value="1" />Yes</label>
	  <label><input type="radio" name="ENABLE" value="0" checked/>No</label>
	  <?php } ?>
	  <br />When set to "Yes", there will be a new post made to your msn space whenever you make a new publishing
		</td>
		</tr>
		<!-- -->
	<tr valign="top">
	<th scope="row">Post Status: </th><td>
	<?php if($WP_MSNSYNC_PUBLISH=="1"){?>
	  <label><input type="radio" name="PUBLISH" value="1" checked/>Published</label>
	  <label><input type="radio" name="PUBLISH" value="0" />Draft</label>
	  <?php }else{ ?>
  	  <label><input type="radio" name="PUBLISH" value="1" />Published</label>
	  <label><input type="radio" name="PUBLISH" value="0" checked/>Draft</label>
	  <?php } ?>
	  <br />Set the status that the synchronized post will appear in MSN spaces.
		</td>
		</tr>
		<!-- -->
	<tr valign="top">
	<th scope="row">Enable Cook: </th><td>
	<?php if($WP_MSNSYNC_COOK=="1"){?>
	  <label><input type="radio" name="COOK" value="1" checked/>Yes</label>
	  <label><input type="radio" name="COOK" value="0" />No</label>
	  <?php }else{ ?>
  	  <label><input type="radio" name="COOK" value="1" />Yes</label>
	  <label><input type="radio" name="COOK" value="0" checked/>No</label>
	  <?php } ?>
	  <br />When set to "Yes", replace "&lt;p&gt;", "&lt;/p&gt;" with "&lt;div&gt;", "&lt;/div&gt; &lt;br/&gt;" to be better viewed with msn spaces.
		</td>
		</tr>
		<!-- -->
	<tr valign="top">
	<th scope="row">Title of Sync:</th><td> <input name="TITLE" type="text" size="60" value="<?php echo  $WP_MSNSYNC_TITLE;?>"/><br />This will appear to be the title of the synchronization post</td></tr>

	<tr valign="top">
	<th scope="row">
	  Content of Sync:
  </th>
  <td>
	  <textarea name="SYNCMSG" cols="60" rows="6"><?php echo $WP_MSNSYNC_MSG;?></textarea>

	  </td>
	  </tr>
	  </TBODY>
	  </TABLE>
	  	  <div class="wrap">You can use <font color="#7799FF">[TITLE]</font> or <font color="#7799FF">[POST]</font></a> in "Title of Sync" and "Content of Sync".<br>
	  They will be replaced by the <font color="#7799FF">Title of your new post</font> or <font color="#7799FF">The content of your new post</font><br>
	  </div>
	<input type="hidden" name="action" value="options" />
	<div align="center"><input value="Save Options" type="submit"/></div>
	</form>
	<div class="wrap" align="right">This plug-in is made by <a href="http://moonblue.homeip.net">William Xu</a> and Modified by priv.</div>
</div>

<?php
}

//move the page to option page
function wp_msnsync_add_page($s){
	add_submenu_page('post.php', 'MSN Sync','MSN Sync',1,__FILE__,'wp_msnsync_display');
	return $s;
}
add_action('admin_menu','wp_msnsync_add_page');
//add_options_page("MSN Sync", "MSN Sync", 1, __FILE__, wp_msnsync_add_page);
//////////////////////////////////////////////////////////////
//Main code section 
//////////////////////////////////////////////////////////////
function wp_msnsync_save(){
	//save options into databse
	update_option("wp_msnsync_url", $_POST['URL']);
	update_option("wp_msnsync_password", $_POST['PASS']);
	update_option("wp_msnsync_enable", $_POST['ENABLE']);
	update_option("wp_msnsync_cook", $_POST['COOK']);
	update_option("wp_msnsync_publish", $_POST['PUBLISH']);
	update_option("wp_msnsync_msg",  stripslashes($_POST['SYNCMSG']));
	update_option("wp_msnsync_title",  stripslashes($_POST['TITLE']));
}

/* Update status on the user space*/
function wp_msnsync_getinfo(){
	global $WP_MSNSYNC_PASSWORD;
	global $WP_MSNSYNC_URL;
	
	$params = array (" ",$WP_MSNSYNC_URL,$WP_MSNSYNC_PASSWORD);
	$method = "blogger.getUsersBlogs";
	$request = xmlrpc_encode_request($method,$params);
	$result=wp_msnsync_docall($request);
	$result_array=xmlrpc_decode($result);
	return $result_array;
}
/* XML RPC Client*/
function wp_msnsync_docall($request){
	$fp = fsockopen("ssl://storage.msn.com", 443, $errno, $errstr);
	if (!$fp) {
	  $hd=@fopen("temp.txt",'a');
	fwrite($hd,"Failed");
	fclose($hd);
	} else {
	$data="";
	$data.="POST /storageservice/MetaWeblog.rpc  HTTP/1.1\r\n";
	$data.="Host: storage.msn.com\r\n";
	$data.="Content-Type: text/xml\r\n";
	$data.="Content-Length: ".strlen($request)."\r\n";
	$data.="Accept: */*\r\n\r\n";
	$data.="$request\r\n\r\n";
	//
	fwrite($fp,$data);
	//
	
	$headers = "";
	do{
		$str = trim(fgets($fp, 128));
		$headers .= "$str\n";
	}while($str!="");
	
	
	/*parse the header for content length*/
	$header_temp=split("\n",$headers);
	foreach($header_temp as $value){
		$temp=split(":",$value);
		$header_array[$temp[0]]=$temp[1];
	}
	if(isset($header_array['Content-Length'])){
	//if size exist
		$size=0 + substr($header_array['Content-Length'],1);
		$body = fread($fp,$size);
	}else{
		$body="";
		while (!feof($fp)) {
			$line.= fgets($fp);

		} 
	}
 
	return $body;
	}

}

//version 1.0 experiment

add_action('publish_post','wp_msnsync_post');



?>
